package com.example.palladium_secure;

/* This class is generated by JADX */
public final class R {

    public static final class attr {
        public static final int activityAction = 2130903040;
        public static final int activityName = 2130903041;
        public static final int alpha = 2130903042;
        public static final int alwaysExpand = 2130903043;
        public static final int animationBackgroundColor = 2130903044;
        public static final int clearTop = 2130903045;
        public static final int finishPrimaryWithPlaceholder = 2130903046;
        public static final int finishPrimaryWithSecondary = 2130903047;
        public static final int finishSecondaryWithPrimary = 2130903048;
        public static final int font = 2130903049;
        public static final int fontProviderAuthority = 2130903050;
        public static final int fontProviderCerts = 2130903051;
        public static final int fontProviderFetchStrategy = 2130903052;
        public static final int fontProviderFetchTimeout = 2130903053;
        public static final int fontProviderPackage = 2130903054;
        public static final int fontProviderQuery = 2130903055;
        public static final int fontProviderSystemFontFamily = 2130903056;
        public static final int fontStyle = 2130903057;
        public static final int fontVariationSettings = 2130903058;
        public static final int fontWeight = 2130903059;
        public static final int lStar = 2130903060;
        public static final int nestedScrollViewStyle = 2130903061;
        public static final int placeholderActivityName = 2130903062;
        public static final int primaryActivityName = 2130903063;
        public static final int queryPatterns = 2130903064;
        public static final int secondaryActivityAction = 2130903065;
        public static final int secondaryActivityName = 2130903066;
        public static final int shortcutMatchRequired = 2130903067;
        public static final int splitLayoutDirection = 2130903068;
        public static final int splitMaxAspectRatioInLandscape = 2130903069;
        public static final int splitMaxAspectRatioInPortrait = 2130903070;
        public static final int splitMinHeightDp = 2130903071;
        public static final int splitMinSmallestWidthDp = 2130903072;
        public static final int splitMinWidthDp = 2130903073;
        public static final int splitRatio = 2130903074;
        public static final int stickyPlaceholder = 2130903075;
        public static final int tag = 2130903076;
        public static final int ttcIndex = 2130903077;
    }

    public static final class color {
        public static final int androidx_core_ripple_material_light = 2130968576;
        public static final int androidx_core_secondary_text_default_material_light = 2130968577;
    }

    public static final class drawable {
        public static final int launch_background = 2131099654;
    }

    public static final class id {
        public static final int accessibility_action_clickable_span = 2131165184;
        public static final int accessibility_custom_action_0 = 2131165185;
        public static final int accessibility_custom_action_1 = 2131165186;
        public static final int accessibility_custom_action_10 = 2131165187;
        public static final int accessibility_custom_action_11 = 2131165188;
        public static final int accessibility_custom_action_12 = 2131165189;
        public static final int accessibility_custom_action_13 = 2131165190;
        public static final int accessibility_custom_action_14 = 2131165191;
        public static final int accessibility_custom_action_15 = 2131165192;
        public static final int accessibility_custom_action_16 = 2131165193;
        public static final int accessibility_custom_action_17 = 2131165194;
        public static final int accessibility_custom_action_18 = 2131165195;
        public static final int accessibility_custom_action_19 = 2131165196;
        public static final int accessibility_custom_action_2 = 2131165197;
        public static final int accessibility_custom_action_20 = 2131165198;
        public static final int accessibility_custom_action_21 = 2131165199;
        public static final int accessibility_custom_action_22 = 2131165200;
        public static final int accessibility_custom_action_23 = 2131165201;
        public static final int accessibility_custom_action_24 = 2131165202;
        public static final int accessibility_custom_action_25 = 2131165203;
        public static final int accessibility_custom_action_26 = 2131165204;
        public static final int accessibility_custom_action_27 = 2131165205;
        public static final int accessibility_custom_action_28 = 2131165206;
        public static final int accessibility_custom_action_29 = 2131165207;
        public static final int accessibility_custom_action_3 = 2131165208;
        public static final int accessibility_custom_action_30 = 2131165209;
        public static final int accessibility_custom_action_31 = 2131165210;
        public static final int accessibility_custom_action_4 = 2131165211;
        public static final int accessibility_custom_action_5 = 2131165212;
        public static final int accessibility_custom_action_6 = 2131165213;
        public static final int accessibility_custom_action_7 = 2131165214;
        public static final int accessibility_custom_action_8 = 2131165215;
        public static final int accessibility_custom_action_9 = 2131165216;
        public static final int action_container = 2131165217;
        public static final int action_divider = 2131165218;
        public static final int action_image = 2131165219;
        public static final int action_text = 2131165220;
        public static final int actions = 2131165221;
        public static final int adjacent = 2131165222;
        public static final int always = 2131165223;
        public static final int alwaysAllow = 2131165224;
        public static final int alwaysDisallow = 2131165225;
        public static final int androidx_window_activity_scope = 2131165226;
        public static final int async = 2131165227;
        public static final int blocking = 2131165228;
        public static final int bottomToTop = 2131165229;
        public static final int chronometer = 2131165230;
        public static final int dialog_button = 2131165231;
        public static final int edit_text_id = 2131165232;
        public static final int forever = 2131165233;
        public static final int fragment_container_view_tag = 2131165234;
        public static final int hide_ime_id = 2131165235;
        public static final int icon = 2131165236;
        public static final int icon_group = 2131165237;
        public static final int info = 2131165238;
        public static final int italic = 2131165239;
        public static final int line1 = 2131165240;
        public static final int line3 = 2131165241;
        public static final int locale = 2131165242;
        public static final int ltr = 2131165243;
        public static final int never = 2131165244;
        public static final int normal = 2131165245;
        public static final int notification_background = 2131165246;
        public static final int notification_main_column = 2131165247;
        public static final int notification_main_column_container = 2131165248;
        public static final int report_drawn = 2131165249;
        public static final int right_icon = 2131165250;
        public static final int right_side = 2131165251;
        public static final int rtl = 2131165252;
        public static final int special_effects_controller_view_tag = 2131165253;
        public static final int tag_accessibility_actions = 2131165254;
        public static final int tag_accessibility_clickable_spans = 2131165255;
        public static final int tag_accessibility_heading = 2131165256;
        public static final int tag_accessibility_pane_title = 2131165257;
        public static final int tag_on_apply_window_listener = 2131165258;
        public static final int tag_on_receive_content_listener = 2131165259;
        public static final int tag_on_receive_content_mime_types = 2131165260;
        public static final int tag_screen_reader_focusable = 2131165261;
        public static final int tag_state_description = 2131165262;
        public static final int tag_transition_group = 2131165263;
        public static final int tag_unhandled_key_event_manager = 2131165264;
        public static final int tag_unhandled_key_listeners = 2131165265;
        public static final int tag_window_insets_animation_callback = 2131165266;
        public static final int text = 2131165267;
        public static final int text2 = 2131165268;
        public static final int time = 2131165269;
        public static final int title = 2131165270;
        public static final int topToBottom = 2131165271;
        public static final int view_tree_lifecycle_owner = 2131165272;
        public static final int view_tree_on_back_pressed_dispatcher_owner = 2131165273;
        public static final int view_tree_saved_state_registry_owner = 2131165274;
        public static final int view_tree_view_model_store_owner = 2131165275;
        public static final int visible_removing_fragment_view_tag = 2131165276;
    }

    public static final class mipmap {
        public static final int launcher_icon = 2131361793;
    }

    public static final class string {
        public static final int androidx_startup = 2131427328;
    }

    public static final class style {
        public static final int LaunchTheme = 2131492864;
        public static final int NormalTheme = 2131492865;
    }
}
